#!/usr/bin/python

import sys

d = {}
f = sys.stdin

for i, line in enumerate(f):
    if i == 0: continue
    for datum in line.split(): d[datum] = i

''' I could also have stored input so as not to need another
pass through stdin'''

f.seek(0) 

for i, line in enumerate(f):
    if i == 0: continue
    x = set(line.split())
    for datum in d.keys():
        if datum not in x: print datum, d[datum], i

print 'done'